
---
- name: Install httpd using Handlers 
  hosts: demo  
  become: true
  gather_facts: yes 
  tasks:
          - name: Install HTTPD on Centos 7 using Handlers
            action: yum name=httpd state=present 
            notify: restart httpd
  handlers: 
          - name: restart httpd
            action: service name=httpd state=restarted

