- name: Setup Application Server
  hosts: all
  become: true

  tasks:
   - name: Install a list of packages with a list variable
     yum:
       name: "{{ packages }}"
     vars:
      packages:
      - httpd
      - httpd-tools
      update_cache: True

